aadilvarsh : added lemon say🍋
lemonsaurus/tyrant pull request #13
Opened 2021-10-02 07:49 UTC by AadilVarsh

### A fun and simple command to answer to a yes/no question with a random response!

#### eg.
```
user#0002   : .say Will I fail my exams?
Tyrant:4342 : Lemon says: Certainly not.
```

### Created 1 file  `tyrant/cogs/lemon_say.py` for the command Cog
### Updated 1 file `tyrant/__main__.py`  to load the Cog

2021-10-05 10:29 UTC, lemonsaurus requested changes
Okay, so I have to request some changes here, especially not duplicating the constants.

In addition to addressing the comments in this review, I want us to have a conversation in the server about what to name this function. I don't like "lemon say". I am not the bot, and I don't want the bot to speak on my behalf. What you're building here is basically a [Magic 8-ball](https://en.wikipedia.org/wiki/Magic_8-Ball) cog, which is fine, but let's name it something along those lines then.

I also think it works just as well if it's the Tyrant who says these things. So, instead of "8-ball says" or "Lemon says:", maybe something like "**The Tyrant** commands: Absolutely not!".

Like, we're making a command here that let's you ask the Tyrant a yes or no question.

2021-10-05 10:29 UTC, lemonsaurus commented on tyrant/cogs/lemon_say.py
> +    """Post answer to generic yes/no questions"""
```suggestion
    """Provide answers for generic yes/no questions."""
```
Docstrings should end with punctuation. See [PEP 257](https://www.python.org/dev/peps/pep-0257/)

2021-10-05 10:29 UTC, lemonsaurus commented on tyrant/cogs/lemon_say.py
> +            ]
Why are you duplicating these into this file? We don't want to do that. 

You are already importing `constants`, which contains all of these strings. It's important that stuff like this has to exist _only in one place_, otherwise if we want to update them, we have to update two files instead of one.

2021-10-05 10:29 UTC, lemonsaurus commented on tyrant/cogs/lemon_say.py
> +        """Initialize this cog with the Bot instance"""
```suggestion
        """Initialize this cog with the Bot instance."""
```

2021-10-05 10:29 UTC, lemonsaurus commented on tyrant/cogs/lemon_say.py
> +        """send random answers to generic yes/no kind of question"""
```suggestion
        """Send random answers to generic yes or no questions."""
```
First letter must be capitalized, punctuation in the end.

2021-10-05 10:29 UTC, lemonsaurus commented on tyrant/cogs/lemon_say.py
> +        await ctx.send(f"**Lemon says :** {random_resp}")
The Tyrant cannot speak on behalf of the Lemon. They are separate entitites.

2021-10-05 10:29 UTC, lemonsaurus commented on tyrant/cogs/lemon_say.py
> +        random_resp = random.choice(self.RESPONSES)
```suggestion
        random_response = random.choice(self.RESPONSES)
```
Code is often read, and rarely written. When you name a variable `resp`, the reader has to figure out what it means from context. Is it a response, or a respirator, or random respect? There's no benefit to being ambiguous, just write `response`. It costs you 4 extra characters, and makes your code marginally more readable. That's a win.

2021-10-05 10:29 UTC, lemonsaurus commented on tyrant/cogs/lemon_say.py
> +    """
```suggestion
    """Add the cog to the bot."""
```
No reason for this to be a multiline docstring. It should be in [imperative mood](https://en.wikipedia.org/wiki/Imperative_mood), and should explain _what its purpose is_, not when it's called.

2021-10-06 03:02 UTC, AadilVarsh commented
Made changes raised in the reviews!

2021-10-07 09:51 UTC, lemonsaurus requested changes
Getting closer. Nice work so far.

When you address these changes, please update the original PR description to match the new functionality, since the original PR body text is now out of date and a bit misleading.

2021-10-07 09:51 UTC, lemonsaurus commented on tyrant/cogs/magic_8_ball.py
> +    """Provide Answers for generic yes or no questions"""
```suggestion
    """Provide answers for generic yes or no questions."""
```
Imperfect docstrings? NEVER! 🍋

2021-10-07 09:51 UTC, lemonsaurus commented on tyrant/cogs/magic_8_ball.py
> +            response_adjective = random.choice(["commands", "orders", "demands", "ordains"])
Okay, firstly we need to swap `dictates` (which has very negative connotations, like `dictator`) with `ordains`, which sounds more positive.

Secondly, I don't think any of these words sound very uncertain. I think we should make a list of uncertain verbs in addition. 
```py
self.uncertain_verbs = [
    `mumbles`, 
    `suggests`, 
    `mutters`, 
    `shrugs, and says`,
]
```

The third thing is that _these are not adjectives_. An adjective would be a word like "blue" or "rancid". These are verbs, aka "doing words". So these variables are incorrectly named.

I also don't think these lists should be created here. That adds complexity. Constants, such as these lists, should be declared as constants at the top of this file, using `SCREAMING_SNAKE_CASE`, or if the constant is universally useful, can be declared in `constants.py`. In this case, I do think these may be universally useful, but it's okay to make them cog constants for now.

2021-10-07 09:51 UTC, lemonsaurus commented on tyrant/cogs/magic_8_ball.py
> +        ]
This is a constant, and should be declared at the top of this file, under the imports, in `SCREAMING_SNAKE_CASE`.

2021-10-07 19:42 UTC, Bluenix2 commented on tyrant/__main__.py
> +bot.load_extension("tyrant.cogs.magic_8_ball")
I think we should have these in alphabetical order.

2021-10-07 19:42 UTC, Bluenix2 commented on tyrant/cogs/magic_8_ball.py
> +class Magic8Ball(Cog):
This should be updated since it is now a "say command".

2021-10-07 19:43 UTC, Bluenix2 commented on tyrant/cogs/magic_8_ball.py
> +        self.uncertain_replies = constants.UNCERTAIN_REPLIES
This doesn't copy the lists

2021-10-07 19:44 UTC, Bluenix2 commented on tyrant/cogs/magic_8_ball.py
> +                self.uncertain_replies.remove(response)
This means that when this cog is loaded, these values will be removed from the constants list as well.

Additionally, this will error if the cog is reloaded.

2021-10-08 03:01 UTC, AadilVarsh commented on tyrant/cogs/magic_8_ball.py
> +class Magic8Ball(Cog):
@Bluenix2 Lemon suggested to use the name Magic8ball...

2021-10-08 05:29 UTC, AadilVarsh commented on tyrant/__main__.py
> +bot.load_extension("tyrant.cogs.magic_8_ball")
Done!

2021-10-08 06:59 UTC, lemonsaurus commented on tyrant/cogs/magic_8_ball.py
> +class Magic8Ball(Cog):
it is a magic 8-ball. it's just one that has a specific "evil tyrant" flavor.

..but this classname may make it harder to find this code for people who go looking for it. We can probably name it something like AskTyrant and ask_tyrant.py.

2021-10-09 22:41 UTC, Bluenix2 commented on tyrant/cogs/magic_8_ball.py
> +class Magic8Ball(Cog):
Are we going forward with this renaming?

2021-10-21 13:37 UTC, lemonsaurus requested changes
Just a few more changes left before this is ready to merge.

2021-10-21 13:37 UTC, lemonsaurus commented on tyrant/__main__.py
> +    ),  # Invoked commands must have this prefix
```suggestion
    command_prefix=when_mentioned_or(constants.Bot.prefix),
```
I don't like this, feels like it has worse readability. Let's put it back in one line, but we can remove the superfluous comment to bring the line length down. This comment isn't very helpful.

2021-10-21 13:37 UTC, lemonsaurus commented on tyrant/cogs/magic_8_ball.py
> +class Magic8Ball(Cog):
still waiting for this change.

2021-10-21 13:37 UTC, lemonsaurus commented on tyrant/cogs/magic_8_ball.py
> +                f'**The Tyrant proclaims **, "You are bad at asking questions"'
```suggestion
                f'**The Tyrant proclaims**, "You are bad at asking questions"'
```
An evil space has snuck in here. 👾

2021-10-21 13:37 UTC, lemonsaurus commented on tyrant/cogs/magic_8_ball.py
> +        """Send random answers to generic yes or no question."""
```suggestion
        """Send random answers to generic yes or no questions."""
```

2021-10-21 13:37 UTC, lemonsaurus commented on tyrant/constants.py
> +UNCERTAIN_VERBS = ["mumbles", "suggests", "mutters", "shrugs, and says"]
```suggestion
POSITIVE_VERBS = ["pronounces", "decrees", "proclaims", "ordains"]
NEGATIVE_VERBS = ["commands", "orders", "demands", "dictates"]
UNCERTAIN_VERBS = ["mumbles", "suggests", "mutters", "shrugs, and says"]
```

These newlines are noisy. A good rule of thumb is that **similar things belong together**. When we group all the verbs together in one chunk, it improves readability.

2021-11-06 04:17 UTC, AadilVarsh commented on tyrant/cogs/ask_tyrant.py
> +            response_verb = random.choice(constants.UNCERTAIN_VERBS)
Yup! thanks I've implemented it :)

2021-11-07 09:29 UTC, lemonsaurus approved these changes
I think this looks good now. Let's merge! 🐱

2021-11-07 09:29 UTC, merged