Custom help command.
lemonsaurus/tyrant pull request #20
Opened 2021-11-27 03:31 UTC by AadilVarsh

### Implemented a custom help command, which returns responses with embeds.

![tyrant-help](https://user-images.githubusercontent.com/72086030/143666596-8d60bc13-3505-4897-a290-31cf850a3306.gif)

2021-11-29 00:14 UTC, Bluenix2 commented
First of all, this looks great!

That said discord.py has built-in ways to create help commands and there's just a few things you need to change to make it work here.

I don't think the actual documentation covers it that nicely, but [I have it implemented in a very simple manor in a bot of mine](https://github.com/Bluenix2/PWBot/blob/master/cogs/meta.py#L10-75). All you need to do is define those same methods, and paste in the code from `create_help_embed()` that you added (but use `self.get_destination()` to get the channel to send the help to, as I do in that code).

Afterwards you need to register it [inside the `__init__()`](https://github.com/Bluenix2/PWBot/blob/master/bot.py#L35-40). The `command_attrs` is used so that the help command itself gets a brief and description here (you can skip that step if you'd like).

For the code that sends the help embeds, just change it to use [`ctx.send_help()`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.Context.send_help).

2021-11-29 02:28 UTC, AadilVarsh commented
@Bluenix2 Hey!

Thanks for the reccomendation, I quickly parsed through the code sample that you had tagged. Yup. That seems great! I'll try to implement it soon.

2021-11-29 19:56 UTC, Bluenix2 commented on tyrant/bot.py
> +            )
Can you undo these changes presumably done by the black linter?

2021-11-29 19:56 UTC, Bluenix2 commented on tyrant/bot.py
> +            )
This one as well.

2021-11-29 19:56 UTC, Bluenix2 commented on tyrant/utils/help.py
> +        bot: Bot = self.context.bot
What's the point of this annotation?

2021-11-29 19:56 UTC, Bluenix2 commented on tyrant/utils/help.py
> +                break
I don't understand, don't you have the command right there as a parameter (called `command`)?

2021-11-29 19:56 UTC, Bluenix2 commented on tyrant/utils/help.py
> +            title="Oops!", description=error, color=constants.Bot.embed_color
Calling `str()` on an error doesn't actually produce a traceback. What you want to do here is use [`traceback.format_exception`](https://docs.python.org/3/library/traceback.html#traceback.format_exception) I think.

The code would look like this:
```python
description = ''.join(traceback.format_exception(type(error), error, error.__traceback__))
```

2021-11-29 19:56 UTC, Bluenix2 commented on tyrant/utils/help.py
> +        super().__init__(*args, **kwargs)
Note: I know this is in my code but it is not required, do feel free to remove this.

2021-12-04 10:44 UTC, AadilVarsh commented on tyrant/utils/help.py
> +        bot: Bot = self.context.bot
I added it for autocompletion, but now that I think of it I'll remove that as well!

2021-12-04 10:55 UTC, AadilVarsh commented on tyrant/utils/help.py
> +            title="Oops!", description=error, color=constants.Bot.embed_color
I havent called str() on the error, it actually returns error as a string.

![image](https://user-images.githubusercontent.com/72086030/144706904-050d9564-799d-4dfb-92b5-4881d858000a.png)

2021-12-04 10:56 UTC, AadilVarsh commented on tyrant/utils/help.py
> +                break
after effects of copypasting!!! fixing it brb.

2021-12-05 22:02 UTC, Bluenix2 commented on tyrant/utils/help.py
> +            title="Oops!", description=error, color=constants.Bot.embed_color
Discord.py will call `str(description)`

2021-12-06 12:50 UTC, lemonsaurus requested changes
This is pretty good, but there's a few more things to address.

2021-12-06 12:50 UTC, lemonsaurus commented on tyrant/utils/help.py
> +            title="Oops!", description=error, color=constants.Bot.embed_color
yeah you do probably want the traceback here.

2022-01-01 18:48 UTC, Bluenix2 commented on .gitignore
> +.vscode
Can you just add this newline here?

2022-01-01 18:48 UTC, Bluenix2 commented on tyrant/utils/help.py
> +        super().__init__()
This can be removed

2022-01-01 18:56 UTC, Bluenix2 commented on tyrant/utils/help.py
> +                field_value += f"**{constants.Bot.prefix}{cmd.name}** [{' | '.join(list(cmd.aliases))}]\n"
This doesn't handle subcommands that well. Instead of `.purge all` this makes it `.all`.

2022-01-20 12:58 UTC, AadilVarsh commented
I've reworked the embed styling of all of the help commands, as mentioned by @Bluenix2  in discord, about the `get_command_signature()`, I've implemented that all along the help commands. 

I've made the command/cog description, character limit to 80. Because if exceeded the entire embed looks shabby, Keeping command help strings short will be ideal for it to be rendered in the embeds. But in Individual command help embeds it will be rendered irrespective of the character length.

# New Embed Style preview.

## Bot Help embed.

![image](https://user-images.githubusercontent.com/72086030/150341317-45bb557a-438a-4b45-8a82-75b846b24dec.png)

> ### You can see there is no description for any of the purge group or its sub commands, this is due to its length exceeding 80 characters.

![image](https://user-images.githubusercontent.com/72086030/150343058-661344f8-5c79-486a-8dcf-eb82c189d3e8.png)

> ### **Commands are also filtered based on user's permissions, Admin POV 👇🏻**

![image](https://user-images.githubusercontent.com/72086030/150341347-1e629722-fc8b-4bc8-b0b4-7957af093bb6.png)

> ### In individual help commands, you can see the description being rendered irrespective of its character length.
![image](https://user-images.githubusercontent.com/72086030/150341803-58a58da6-d624-4497-a27d-c5ab6490139b.png)

2022-01-20 14:13 UTC, Bluenix2 commented
This looks amazing, I'll give it a last test later today!

2022-01-20 22:19 UTC, Bluenix2 approved these changes
This is great! Thank you for being patient with me here 😅.

2022-01-21 16:26 UTC, AadilVarsh commented
> This is great! Thank you for being patient with me here 😅.

Haha, It's actually the other way around. Thank you for the reviews!

2022-02-01 13:01 UTC, lemonsaurus commented on tyrant/utils/help.py
> +            for cmd in cog_commands:
We can afford to write the word `command` instead of just `cmd`. There's really no advantage to this sort of shorthand, it just looks lazy.

2022-02-01 13:01 UTC, lemonsaurus commented on tyrant/utils/help.py
> +
No newlines after coroutine docstrings.

```suggestion
```

2022-02-01 13:03 UTC, lemonsaurus commented on tyrant/utils/help.py
> +        await self.get_destination().send(embed=help_embed)
This coroutine needs more _block comments_. Someone who is skimming through this file should be able to understand roughly what you're doing without reading your source code, just from the block comments. A block comment every 5-10 lines is a good rule of thumb. Obviously don't just _arbitrarily_ make block comments, make them for a logical block of code that accomplishes one specific thing.

2022-02-01 13:03 UTC, lemonsaurus commented on tyrant/utils/help.py
> +            help_embed.add_field(name=command.name.title(), value=f"{description if len(description) <= 80 else ''}{cmd}", inline=False)
This line is way too dense, too much cognitive complexity. Please refactor.

2022-02-01 13:03 UTC, lemonsaurus commented on tyrant/utils/help.py
> +        msg = (group.help if group.description == "" else group.description)
`message`

2022-02-01 15:44 UTC, lemonsaurus commented
@AadilVarsh Also, when you address review comments, would you mind resolving the comments in this thread? That way, we can see which ones you've already addressed.

2022-02-01 16:28 UTC, AadilVarsh commented
> @AadilVarsh Also, when you address review comments, would you mind resolving the comments in this thread? That way, we can see which ones you've already addressed.

I'm sorry, I didn't see this comment. I've resolved all of the requested changes.

2022-02-02 11:17 UTC, lemonsaurus approved these changes
Alright, let's do this.

2022-02-02 11:17 UTC, merged